security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Admin: 'auto'

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: admin_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /event/crud
                enable_csrf: true
                csrf_token_id: authenticate
            logout:
                path: /logout
                target: /login
                

    access_control:
        - { path: ^/login$, allow_if: "!is_granted('ROLE_ADMIN')" }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/event/crud/.*, roles: ROLE_ADMIN }