security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Admin: 'auto'
        App\Entity\Teacher: 'auto'

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        teacher_provider:
            id: App\Security\TeacherUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        teacher:
            pattern: ^/teacher
            lazy: true
            provider: teacher_provider
            form_login:
                login_path: teacher_login
                check_path: teacher_login
                default_target_path: /teacher/dashboard
                enable_csrf: true
                csrf_token_id: authenticate
            logout:
                path: /teacher/logout
                target: /teacher/login

        main:
            lazy: true
            provider: admin_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /event/crud
                enable_csrf: true
                csrf_token_id: authenticate
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/login$, allow_if: "!is_granted('ROLE_ADMIN')" }
        - { path: ^/teacher/login$, allow_if: "!is_granted('ROLE_TEACHER')" }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/event/crud/.*, roles: ROLE_ADMIN }
        - { path: ^/teacher/dashboard, roles: ROLE_TEACHER }
        - { path: ^/teacher/events, roles: ROLE_TEACHER }
        - { path: ^/teacher/events/create, roles: ROLE_TEACHER }
        - { path: ^/teacher/events/availability, roles: ROLE_TEACHER }
        - { path: ^/event/crud/pending, roles: ROLE_ADMIN }
        - { path: ^/event/crud/approve, roles: ROLE_ADMIN }
        - { path: ^/event/crud/reject, roles: ROLE_ADMIN }
        - { path: ^/admin/create, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon