controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    controller: lexik_jwt_authentication.security.jwt_authenticator:authenticate
